// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvptdcpbmoullhptxjhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cHRkY3BibW91bGxocHR4amhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTk5NDAsImV4cCI6MjA2MjA5NTk0MH0.jv26F5lxzY95KBUf8PCrZegqdY3UMmA8H5Zd6R5VvdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);